### ISSUE TITLE
rtplot_server_on value in hdriver config file set to false every time you quit hdriver

### ISSUE THREAD

**Issue by vikdhillon** [HiPERCAM/hcam-drivers#115] opened 2018-05-21 14:02 UTC
Every time you quit hdriver, the rtplot_server_on value in the config file in .hdriver is set to false even though it had previously been set to true by the user (by hand editing the config file).

**Comment by StuartLittlefair** [comment] 2018-06-01 13:50
This is a subtle issue caused by the fact that I think you were editing the file *whilst hdriver is itself running*. 

```hdriver``` saves it's internal config when closing, so the chain of events is

1. load hdriver, read config file, set ```rtplot_server_on``` to False inside hdriver
2. Edit config file, set rtplot_server_on to True inside file
3. Quit hdriver, saving internal state, in which rtplot_server_on is still False.

So although annoying I think this is correct behaviour. I'll close this issue. @vikdhillon can kick up a fuss if he disagrees!

**Closed as completed by StuartLittlefair** 2018-06-01 13:50 UTC
